### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [purveshpatel511/plain-ui#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by purveshpatel511** [comment]
@unixorn, I added screenshot into readme file. Hope you like this theme.

**Comment by unixorn** [comment]
Thanks!
